# Netlify Configuration for CD Practices App

[build]
  command = "npm run build"
  publish = "build"

  [build.environment]
    NODE_VERSION = "24.8.0"
    # Database migrations run automatically via npm run build
    # which calls db:migrate before building the app

# Build plugins - Install PostgreSQL client for migrations
[[plugins]]
  package = "essential-postgres"

# Security headers
[[headers]]
  for = "/*"
  [headers.values]
    Permissions-Policy     = "geolocation=(), microphone=(), camera=()"
    Referrer-Policy        = "strict-origin-when-cross-origin"
    X-Content-Type-Options = "nosniff"
    X-Frame-Options        = "DENY"
    X-XSS-Protection       = "1; mode=block"

# Cache static assets
[[headers]]
  for = "/_app/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

# Cache API responses (5 minutes)
[[headers]]
  for = "/api/*"
  [headers.values]
    Cache-Control = "public, max-age=300, s-maxage=600, stale-while-revalidate=300"

# Postgres addon configuration
[functions]
  external_node_modules = [
    "pg"
  ]
  node_bundler = "esbuild"

# Environment-specific settings
# Production uses DATABASE_URL from Netlify environment variables

# Deploy Previews (Pull Request previews)
[context.deploy-preview]
  [context.deploy-preview.environment]
    NODE_ENV = "development"
    # DATABASE_URL = "set this in Netlify UI for deploy-preview context"
    # Or use DEPLOY_PREVIEW_DATABASE_URL from environment variables

# Branch Deploys (non-production branches)
[context.branch-deploy]
  [context.branch-deploy.environment]
    NODE_ENV = "development"
    # DATABASE_URL = "set this in Netlify UI for branch-deploy context"
    # Or use BRANCH_DEPLOY_DATABASE_URL from environment variables
