# Netlify Configuration for CD Practices App

[build]
  command = "npm run build"
  publish = "build"

  [build.environment]
    NODE_VERSION = "24.8.0"

# Security headers
[[headers]]
  for = "/*"
  [headers.values]
    Permissions-Policy     = "geolocation=(), microphone=(), camera=()"
    Referrer-Policy        = "strict-origin-when-cross-origin"
    X-Content-Type-Options = "nosniff"
    X-Frame-Options        = "DENY"
    X-XSS-Protection       = "1; mode=block"

# Cache static assets
[[headers]]
  for = "/_app/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

# Cache API responses (5 minutes)
[[headers]]
  for = "/api/*"
  [headers.values]
    Cache-Control = "public, max-age=300, s-maxage=600, stale-while-revalidate=300"

# Postgres addon configuration
[functions]
  external_node_modules = [
    "pg"
  ]
  node_bundler = "esbuild"

# Environment-specific settings
[context.deploy-preview]
  environment = { NODE_ENV = "development" }

[context.branch-deploy]
  environment = { NODE_ENV = "development" }
