name: Release Please (with PAT)

on:
  workflow_dispatch:
  push:
    branches:
      - main

# No top-level permissions needed when using PAT
# The PAT's permissions override these

jobs:
  release-please:
    runs-on: ubuntu-latest
    steps:
      - uses: googleapis/release-please-action@v4
        id: release
        with:
          # Use PAT instead of GITHUB_TOKEN
          token: ${{ secrets.RELEASE_PLEASE_TOKEN }}
          # No target-branch: creates Release PR on main

      # Checkout repository for subsequent steps
      - name: Checkout
        if: ${{ steps.release.outputs.release_created }}
        uses: actions/checkout@v4
        with:
          fetch-depth: 0 # Fetch all history for all branches
          # Use PAT for checkout to allow pushing to protected branches
          token: ${{ secrets.RELEASE_PLEASE_TOKEN }}

      # Update release branch when Release PR is merged
      - name: Update release branch
        if: ${{ steps.release.outputs.release_created }}
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"

          # Fetch latest
          git fetch origin main
          git fetch origin release || true

          # Force update release branch to match main
          git checkout -B release origin/main
          git push origin release --force
