name: Release Please

on:
  workflow_dispatch:
  workflow_run:
    workflows: ['CI Flow']
    types:
      - completed
    branches:
      - main

permissions:
  contents: write
  pull-requests: write

jobs:
  release-please:
    runs-on: ubuntu-latest
    # Only run if tests passed
    if: ${{ github.event.workflow_run.conclusion == 'success' || github.event_name == 'workflow_dispatch' }}
    steps:
      - uses: googleapis/release-please-action@v4
        id: release
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      # Checkout repository when a release is created (PR merged)
      - name: Checkout
        if: ${{ steps.release.outputs.release_created }}
        uses: actions/checkout@v4
        with:
          ref: main
          fetch-depth: 0

      # Update release branch when Release PR is merged
      - name: Update release branch
        if: ${{ steps.release.outputs.release_created }}
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"

          # Delete remote release branch if it exists
          git push origin --delete release || echo "No existing release branch to delete"

          # Create and push new release branch from current main
          git checkout -b release
          git push origin release

          echo "Release branch updated to $(git rev-parse HEAD)"

      - name: Output release info
        if: ${{ steps.release.outputs.release_created }}
        run: |
          echo "Release created: ${{ steps.release.outputs.tag_name }}"
          echo "Release branch updated for Netlify deployment"
