name: Release Please

on:
  workflow_run:
    workflows: ['Run Tests'] # Wait for CI workflow to complete
    types:
      - completed
    branches:
      - main

permissions:
  contents: write
  pull-requests: write

jobs:
  release-please:
    runs-on: ubuntu-latest
    # Only run if CI workflow succeeded
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    steps:
      - uses: googleapis/release-please-action@v4
        id: release
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          # No target-branch: creates Release PR on main

      # Checkout repository for subsequent steps
      - name: Checkout
        if: ${{ steps.release.outputs.release_created }}
        uses: actions/checkout@v4
        with:
          fetch-depth: 0  # Fetch all history for all branches

      # Update release branch when Release PR is merged
      - name: Update release branch
        if: ${{ steps.release.outputs.release_created }}
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"

          # Fetch latest
          git fetch origin main
          git fetch origin release || true

          # Force update release branch to match main
          git checkout -B release origin/main
          git push origin release --force
